version: "3"
services:
    app:
        container_name: node_api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/usr/src/app
        ports:
            - "3000:3000"
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'
